
POST http://127.0.0.1:8000/auth/signup/ 
Content-Type: application/json 

{"username": "adminuser", "password": "admin", "email": "adam@mail4.com","first_name":"mama", "last_name":"woman" }

###

POST http://127.0.0.1:8000/auth/login/
Content-Type: application/json 

{ "username": "kofi", "password": "Pass1234" }


###
POST http://127.0.0.1:8000/auth/logout/
Content-Type: application/json 


###
GET http://127.0.0.1:8000/auth/user/ 
Content-Type: application/json 

###
GET http://127.0.0.1:8000/auth/user
Content-Type: application/json 


###
GET http://127.0.0.1:8000/product/products/ 
Content-Type: application/json 

###
GET http://127.0.0.1:8000/product/arrivalproduct/ACCRA/ 
Content-Type: application/json 






###

GET http://127.0.0.1:8000/auth/test_token 
Content-Type: application/json 
Authorization: Token 86819d65eb408c774543688e19ee16d4acbd8ef8