
POST http://127.0.0.1:8000/auth/signup/ 
Content-Type: application/json 

{"username": "kofi4", "password": "Pass1234!", "email": "adam@mail4.com","first_name":"mama" }

###

POST http://127.0.0.1:8000/auth/login/ 

{ "username": "adam", "password": "Pass1234!" }

###

GET http://127.0.0.1:8000/auth/test_token 