# Generated by Django 4.2.6 on 2023-11-30 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sender_name', models.CharField(max_length=150)),
                ('sender_contact', models.CharField(max_length=10)),
                ('sender_email', models.EmailField(default='', max_length=100)),
                ('sender_address', models.CharField(max_length=100)),
                ('sender_location', models.CharField(max_length=100)),
                ('product', models.TextField(max_length=150)),
                ('product_code', models.CharField(max_length=150)),
                ('quantity', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('item_type', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=150)),
                ('handle_preference', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('reciever_name', models.CharField(max_length=150)),
                ('reciever_contact', models.CharField(max_length=10)),
                ('reciever_email', models.EmailField(default='', max_length=100)),
                ('reciever_address', models.CharField(max_length=100)),
                ('reciever_location', models.CharField(max_length=100)),
                ('shipping_confirmation', models.BooleanField(null=True)),
                ('arrival_confirmation', models.BooleanField(null=True)),
                ('product_status', models.CharField(max_length=100)),
                ('is_cancel', models.BooleanField(default=False)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('User', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
