# Generated by Django 4.2.6 on 2023-11-20 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='attendant',
            new_name='User',
        ),
    ]
