# Generated by Django 4.2.6 on 2023-12-14 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product',
            new_name='product_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='product',
            name='reciever_email',
        ),
        migrations.RemoveField(
            model_name='product',
            name='reciever_location',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sender_address',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sender_email',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
    ]
