# Generated by Django 4.2.6 on 2023-11-20 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_attendant_product_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='status',
            new_name='product_status',
        ),
    ]
