# Generated by Django 4.2.6 on 2023-12-15 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_product_product_product_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_code',
            new_name='package_code',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='package_name',
        ),
    ]
