# Generated by Django 4.2.6 on 2023-12-15 00:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shipping', '0002_drop'),
        ('product', '0003_rename_product_code_product_package_code_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Package',
        ),
    ]
