# Generated by Django 4.2.6 on 2023-11-27 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_arrival_confirmation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='reciever_email',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='sender_email',
            field=models.EmailField(default='', max_length=100),
        ),
    ]
