# Generated by Django 4.2.6 on 2023-11-28 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_rename_datetime_product_recieve_datetime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='recieve_datetime',
            new_name='datetime',
        ),
        migrations.RemoveField(
            model_name='product',
            name='arrival_datetime',
        ),
        migrations.RemoveField(
            model_name='product',
            name='delivered_datetime',
        ),
        migrations.RemoveField(
            model_name='product',
            name='shipping_datetime',
        ),
    ]
