# Generated by Django 4.2.6 on 2023-11-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('role', models.CharField(default='', max_length=100)),
                ('address', models.CharField(max_length=60)),
                ('telephone', models.CharField(max_length=15)),
                ('ghanacard_no', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
