# Generated by Django 4.2.6 on 2023-12-13 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_rename_user_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='User',
            new_name='admin',
        ),
    ]
