# Generated by Django 4.2.6 on 2023-12-13 11:25

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_profile_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileImage',
            field=models.ImageField(blank=True, null=True, upload_to=authentication.models.upload_path),
        ),
    ]
