# Generated by Django 4.2.6 on 2023-12-13 13:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_profile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='User',
        ),
        migrations.AddField(
            model_name='profile',
            name='admin',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
