# Generated by Django 4.2.6 on 2023-12-13 15:46

import authentication.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0014_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('role', models.CharField(default='', max_length=100)),
                ('address', models.CharField(max_length=60)),
                ('telephone', models.CharField(max_length=15)),
                ('ghanacard_no', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=100)),
                ('profileImage', models.ImageField(blank=True, upload_to=authentication.models.upload_path)),
                ('date_created', models.DateTimeField(auto_now=True, null=True)),
                ('User', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
