# Generated by Django 4.2.6 on 2023-12-13 16:32

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_profile_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileImage',
            field=models.ImageField(blank=True, null=True, upload_to=authentication.models.upload_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('worker', 'worker'), ('driver', 'driver'), ('admin', 'admin')], max_length=100),
        ),
    ]
