# Generated by Django 4.2.6 on 2023-11-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_rename_ships_ship'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='product',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='ship',
            name='driver',
            field=models.CharField(max_length=150),
        ),
    ]
