# Generated by Django 4.2.6 on 2023-11-28 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0003_ship_product_alter_ship_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='develered',
            field=models.BooleanField(default=True),
        ),
    ]
